---
x-logging:
  &default-logging
  options:
    max-size: "100k"
    max-file: "5"
  driver: json-file

services:
  #=============================================================================
  # media servers
  #=============================================================================

  plex:
    image: linuxserver/plex
    container_name: plex
    logging: *default-logging
    runtime: ${PLEX_RUNTIME:-runc}
    labels:
      - autoheal=true
    environment:
      # plex
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - VERSION=latest
      # nvidia
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      # nginx-proxy
      - "VIRTUAL_HOST=\
          ${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=32400
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    ports:
      - ${PLEX_PORT:-32400}:32400
    volumes:
      - ./cache/plex:/transcode
      - ./config/plex:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    healthcheck:
        test:
          - CMD
          - /bin/bash
          - -c
          - curl -fsSL -m5 http://127.0.0.1:32400/web/index.html >/dev/null && ( [[ ! -a /dev/nvidia0 ]] || nvidia-smi >/dev/null )
        interval: 10s
        timeout: 8s
        retries: 3
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      # tautulli
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      # nginx-proxy
      - "VIRTUAL_HOST=\
          tautulli.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^tautulli\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=tautulli.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=8181
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=tautulli.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/plex/Library/Application Support/Plex Media Server/Logs:/logs
      - ./config/tautulli:/config
    restart: unless-stopped

  kavita:
    image: kizaing/kavita:nightly
    container_name: kavita
    logging: *default-logging
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      # nginx-proxy
      - "VIRTUAL_HOST=\
          read.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^read\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=read.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=5000
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=read.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/kavita:/kavita/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    restart: unless-stopped

  #=============================================================================
  # media management
  #=============================================================================

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    logging: *default-logging
    environment:
      # sonarr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - XDG_CONFIG_HOME=/tmp/xdg
      # nginx-proxy
      - "VIRTUAL_HOST=\
          sonarr.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^sonarr\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=sonarr.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=8989
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=sonarr.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/sonarr:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    depends_on:
      - prowlarr
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    logging: *default-logging
    environment:
      # radarr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - XDG_CONFIG_HOME=/tmp/xdg
      # nginx-proxy
      - "VIRTUAL_HOST=\
          radarr.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^radarr\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=radarr.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=7878
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=radarr.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/radarr:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    depends_on:
      - prowlarr
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    logging: *default-logging
    environment:
      # lidarr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - XDG_CONFIG_HOME=/tmp/xdg
      # nginx-proxy
      - "VIRTUAL_HOST=\
          lidarr.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^lidarr\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=lidarr.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=8686
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=lidarr.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/lidarr:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    depends_on:
      - prowlarr
    restart: unless-stopped

  readarr:
    image: ghcr.io/linuxserver/readarr:nightly
    container_name: readarr
    logging: *default-logging
    environment:
      # readarr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - XDG_CONFIG_HOME=/tmp/xdg
      # nginx-proxy
      - "VIRTUAL_HOST=\
          readarr.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^readarr\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=readarr.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=8787
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=readarr.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/readarr:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr
    container_name: overseerr
    logging: *default-logging
    environment:
      # overseerr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      # nginx-proxy
      - "VIRTUAL_HOST=\
          requests.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^requests\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=requests.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=5055
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=requests.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/overseerr:/config
    restart: unless-stopped

  #=============================================================================
  # indexer middleware
  #=============================================================================

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    logging: *default-logging
    environment:
      # prowlarr
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - XDG_CONFIG_HOME=/tmp/xdg
      # nginx-proxy
      - "VIRTUAL_HOST=\
          prowlarr.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^prowlarr\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=prowlarr.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=9696
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=prowlarr.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/prowlarr:/config
    depends_on:
      - vpn
    restart: unless-stopped

  #=============================================================================
  # download clients
  #=============================================================================

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    logging: *default-logging
    environment:
      # nzbget
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      # nginx-proxy
      - "VIRTUAL_HOST=\
          nzbget.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^nzbget\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=nzbget.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=6789
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=nzbget.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/nzbget:/config
      - ./media:/media
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    logging: *default-logging
    network_mode: service:vpn
    entrypoint: /usr/local/bin/init
    labels:
      - autoheal=true
    environment:
      # deluge
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - UMASK=002
      # vpn
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
      # nginx-proxy
      - NETWORK_ACCESS=internal
    volumes:
      - ./config/deluge:/config
      - ./config/vpn:/gluetun:ro
      - ./media:/media
      - ./share/deluge/init:/usr/local/bin/init
      # Optional volumes, e.g. to follow symlinks
      - ${EXTRA_DATA_VOL_0:-/dev/null}:${EXTRA_DATA_VOL_0:-/dev/.null/0}
      - ${EXTRA_DATA_VOL_1:-/dev/null}:${EXTRA_DATA_VOL_1:-/dev/.null/1}
      - ${EXTRA_DATA_VOL_2:-/dev/null}:${EXTRA_DATA_VOL_2:-/dev/.null/2}
      - ${EXTRA_DATA_VOL_3:-/dev/null}:${EXTRA_DATA_VOL_3:-/dev/.null/3}
      - ${EXTRA_DATA_VOL_4:-/dev/null}:${EXTRA_DATA_VOL_4:-/dev/.null/4}
      - ${EXTRA_DATA_VOL_5:-/dev/null}:${EXTRA_DATA_VOL_5:-/dev/.null/5}
    healthcheck:
        test:
          - CMD
          - /bin/bash
          - -c
          - curl -fsSL -m5 http://127.0.0.1:8112
        interval: 10s
        timeout: 8s
        retries: 3
    depends_on:
      - vpn
    restart: unless-stopped

  #=============================================================================
  # http reverse proxy
  #=============================================================================

  nginx:
    image: nginxproxy/nginx-proxy
    container_name: nginx
    logging: *default-logging
    ports:
      - ${HTTP_PORT:-8080}:80
      - ${HTTPS_PORT:-8443}:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/nginx.tmpl:/app/nginx.tmpl
      - ./config/nginx/certs:/etc/nginx/certs
      - ./config/nginx/certs:/etc/nginx/dhparam
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/vhost.d:/etc/nginx/vhost.d
      - ./share/nginx/html:/usr/share/nginx/html
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    logging: *default-logging
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/nginx/acme.sh:/etc/acme.sh
    depends_on:
      - nginx
    restart: unless-stopped

  #=============================================================================
  # privacy
  #=============================================================================

  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    logging: *default-logging
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 8112
    ports:
      # http-proxy
      - 8888:8888
    environment:
      # mullvad
      - CITY=${MULLVAD_CITY:-London}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
      - HTTPPROXY=on
      - VPN_TYPE=wireguard
      - VPNSP=mullvad
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS:-10.64.222.21/32}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      # nginx-proxy
      - "VIRTUAL_HOST=\
          deluge.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^deluge\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=deluge.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=8112
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=deluge.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - ./config/vpn:/gluetun
    restart: unless-stopped

  #=============================================================================
  # container management
  #=============================================================================

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    logging: *default-logging
    security_opt:
      - no-new-privileges
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  portainer:
    image: ${PORTAINER_IMAGE:-portainer/portainer-ce}
    container_name: portainer
    logging: *default-logging
    environment:
      # portainer
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - VERSION=docker
      # nginx-proxy
      - "VIRTUAL_HOST=\
          portainer.${HTTP_HOST:-127.0.0.1.sslip.io},\
          ~^portainer\\.[0-9a-f:.-]+\\.sslip\\.io$$"
      - CERT_NAME=portainer.${HTTP_HOST:-127.0.0.1.sslip.io}
      - VIRTUAL_PORT=9000
      # acme-companion
      - ${LE_HOST_KEY:-NGINX_SSL_HOST}=portainer.${HTTP_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/portainer:/data
    restart: unless-stopped

  #=============================================================================
  # host management
  #=============================================================================

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    logging: *default-logging
    environment:
      # ddclient
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      # nginx-proxy
      - NETWORK_ACCESS=internal
    volumes:
      - ./config/ddclient:/config
    restart: unless-stopped
