#!/bin/bash

cd "$DOKARR_PATH"

BACKUP_FILENAME="dokarr-$(date '+%Y%m%d_%H%M').tgz"
BACKUP_FILEPATH="$PWD/backups/$BACKUP_FILENAME"

echo -n "Creating backup $BACKUP_FILEPATH ... " >&2

tar zcf "$BACKUP_FILEPATH" \
    --exclude='config/plex/Library/Application Support/Plex Media Server/Cache/*' \
    --exclude='config/plex/Library/Application Support/Plex Media Server/Crash Reports/*' \
    --exclude='config/plex/Library/Application Support/Plex Media Server/Logs/*' \
    --exclude='config/plex/Library/Application Support/Plex Media Server/Media/*' \
    --exclude='config/plex/Library/Application Support/Plex Media Server/Metadata/*' \
    --exclude='config/*/MediaCover/*' \
    --exclude='config/*/logs/*' \
    --exclude='config/deluge/state/*' \
    --exclude='config/deluge/dht.state' \
    --exclude='config/jackett/Jackett/log.txt*' \
    --exclude='desktop.ini' \
    --exclude='*~' \
    --exclude='*.bak' \
    --exclude='*.db-20*' \
    --exclude='*.git*' \
    --exclude='*.log*' \
    --exclude='*.pid' \
    --exclude='.DS_Store' \
    config/ .env

echo "OK" >&2
