#!/bin/bash

cd "$DOKARR_PATH"

DOCKER_MACHINE_IP=$(docker-machine ip "$DOKARR_MACHINE_NAME")

# build commands to initialize docker-machine
SSH_COMMAND=( "ssh" "-i" "~/.docker/machine/machines/$DOKARR_MACHINE_NAME/id_rsa" )
SSH_COMMAND=( "${SSH_COMMAND[@]}" "-o" "StrictHostKeyChecking=no" )
SSH_COMMAND=( "${SSH_COMMAND[@]}" "-o" "UserKnownHostsFile=/dev/null" )
SSH_COMMAND=( "${SSH_COMMAND[@]}" "docker@$DOCKER_MACHINE_IP" )
RSYNC_COMMAND=( "rsync" "-rlc" "-e" "'${SSH_COMMAND[@]}'" "machine/boot2docker/" ":/tmp/boot2docker/" )

# rsync the bootsync file to the remote
eval "${RSYNC_COMMAND[@]}"

# execute the commands on the remote
cat <<EOF | "${SSH_COMMAND[@]}" sudo bash
cd /var/lib/boot2docker

# create the .env file to be used with bootsync and bootlocal
touch .env && chmod 0600 .env
cat <<ENV >.env
COMPOSE_VERSION=$COMPOSE_VERSION
CIFS_USERNAME=$CIFS_USERNAME
CIFS_PASSWORD=$CIFS_PASSWORD
CIFS_VERSION=$CIFS_VERSION
CIFS_EXTRA_OPTS=$CIFS_EXTRA_OPTS
SSH_PUBLIC_KEY_0="${SSH_PUBLIC_KEY_0:-}"
SSH_PUBLIC_KEY_1="${SSH_PUBLIC_KEY_1:-}"
SSH_PUBLIC_KEY_2="${SSH_PUBLIC_KEY_2:-}"
SSH_PUBLIC_KEY_3="${SSH_PUBLIC_KEY_3:-}"
SSH_PUBLIC_KEY_4="${SSH_PUBLIC_KEY_4:-}"
SHARE_PATH=$DOKARR_PATH
ENV

rsync -rlc /tmp/boot2docker/ .
rm -rf /tmp/boot2docker
./bootsync.sh
sudo -u docker tar xf userdata.tar -C /home/docker
./bootlocal.sh
EOF
