#!/bin/bash

PIA_API_HOST=209.222.18.222:2000
LTCONFIG_GITHUB_REPO=ratanakvlun/deluge-ltconfig

cd /config

# wait for vpn interface creation
while ! [[ -L /sys/class/net/tun0 ]]; do
    echo "Waiting for tun0 to become available" >&2
    sleep 1
done

# create initial config files
for dist in $(ls *.conf-dist); do
    conf="${dist:0:${#dist}-5}"
    if [[ ! -f "$conf" ]]; then
        cp "$dist" "$conf"
    fi
done

echo "Detected remote ip address: $(curl -s https://api.ipify.org)" >&2

# request pia port forwarding
echo -n "Detecting forwarded port ... " >&2

if [[ -f /gluetun/forwarded_port ]]; then
    LISTEN_PORT=$(grep -E '[0-9]+' /gluetun/forwarded_port)
    echo "OK" >&2
    echo "Updating deluge config to use port: $LISTEN_PORT" >&2
    cp -f core.conf core.conf~
    cat core.conf~ | perl -0777 -pe 's/"listen_ports":.+?\]/"listen_ports": [\n        '$LISTEN_PORT',\n        '$LISTEN_PORT'\n    ]/ms' > core.conf
else
    echo "ERR" >&2
fi

# create plugins directory
mkdir plugins 2>/dev/null
cd plugins

# download ltConfig
if [[ ! -f ltConfig-*.egg ]]; then
    echo -n "Downloading ltConfig ... " >&2
    PLUGIN_URL=$(curl -sSL https://api.github.com/repos/ratanakvlun/deluge-ltconfig/releases/latest \
        | grep 'browser_download_url' \
        | cut -d '"' -f4)
    PLUGIN_FILE=$(basename "$PLUGIN_URL")
    curl -sSL --output "$PLUGIN_FILE" "$PLUGIN_URL"
    [[ $? == 0 ]] && echo "OK" 2>&1 || "ERR" 2>&1
fi

# start deluge
cd ~/
exec /init
