PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "VersionInfo" ("Version" INTEGER NOT NULL, "AppliedOn" DATETIME, "Description" TEXT);
INSERT INTO VersionInfo VALUES(1,'2019-03-25T00:00:00','InitialSetup');
INSERT INTO VersionInfo VALUES(2,'2019-03-25T00:00:00','remove_tvrage_imdb_unique_constraint');
INSERT INTO VersionInfo VALUES(3,'2019-03-25T00:00:00','remove_renamed_scene_mapping_columns');
INSERT INTO VersionInfo VALUES(4,'2019-03-25T00:00:00','updated_history');
INSERT INTO VersionInfo VALUES(5,'2019-03-25T00:00:00','added_eventtype_to_history');
INSERT INTO VersionInfo VALUES(6,'2019-03-25T00:00:00','add_index_to_log_time');
INSERT INTO VersionInfo VALUES(7,'2019-03-25T00:00:00','add_renameEpisodes_to_naming');
INSERT INTO VersionInfo VALUES(8,'2019-03-25T00:00:00','remove_backlog');
INSERT INTO VersionInfo VALUES(9,'2019-03-25T00:00:00','fix_rename_episodes');
INSERT INTO VersionInfo VALUES(10,'2019-03-25T00:00:00','add_monitored');
INSERT INTO VersionInfo VALUES(11,'2019-03-25T00:00:00','remove_ignored');
INSERT INTO VersionInfo VALUES(12,'2019-03-25T00:00:00','remove_custom_start_date');
INSERT INTO VersionInfo VALUES(13,'2019-03-25T00:00:00','add_air_date_utc');
INSERT INTO VersionInfo VALUES(14,'2019-03-25T00:00:00','drop_air_date');
INSERT INTO VersionInfo VALUES(15,'2019-03-25T00:00:00','add_air_date_as_string');
INSERT INTO VersionInfo VALUES(16,'2019-03-25T00:00:00','updated_imported_history_item');
INSERT INTO VersionInfo VALUES(17,'2019-03-25T00:00:00','reset_scene_names');
INSERT INTO VersionInfo VALUES(18,'2019-03-25T00:00:00','remove_duplicates');
INSERT INTO VersionInfo VALUES(19,'2019-03-25T00:00:00','restore_unique_constraints');
INSERT INTO VersionInfo VALUES(20,'2019-03-25T00:00:00','add_year_and_seasons_to_series');
INSERT INTO VersionInfo VALUES(21,'2019-03-25T00:00:00','drop_seasons_table');
INSERT INTO VersionInfo VALUES(22,'2019-03-25T00:00:00','move_indexer_to_generic_provider');
INSERT INTO VersionInfo VALUES(23,'2019-03-25T00:00:00','add_config_contract_to_indexers');
INSERT INTO VersionInfo VALUES(24,'2019-03-25T00:00:00','drop_tvdb_episodeid');
INSERT INTO VersionInfo VALUES(25,'2019-03-25T00:00:00','move_notification_to_generic_provider');
INSERT INTO VersionInfo VALUES(26,'2019-03-25T00:00:00','add_config_contract_to_notifications');
INSERT INTO VersionInfo VALUES(27,'2019-03-25T00:00:00','fix_omgwtfnzbs');
INSERT INTO VersionInfo VALUES(28,'2019-03-25T00:00:00','add_blacklist_table');
INSERT INTO VersionInfo VALUES(29,'2019-03-25T00:00:00','add_formats_to_naming_config');
INSERT INTO VersionInfo VALUES(30,'2019-03-25T00:00:00','add_season_folder_format_to_naming_config');
INSERT INTO VersionInfo VALUES(31,'2019-03-25T00:00:00','delete_old_naming_config_columns');
INSERT INTO VersionInfo VALUES(32,'2019-03-25T00:00:00','set_default_release_group');
INSERT INTO VersionInfo VALUES(33,'2019-03-25T00:00:00','add_api_key_to_pushover');
INSERT INTO VersionInfo VALUES(34,'2019-03-25T00:00:00','remove_series_contraints');
INSERT INTO VersionInfo VALUES(35,'2019-03-25T00:00:00','add_series_folder_format_to_naming_config');
INSERT INTO VersionInfo VALUES(36,'2019-03-25T00:00:00','update_with_quality_converters');
INSERT INTO VersionInfo VALUES(37,'2019-03-25T00:00:00','add_configurable_qualities');
INSERT INTO VersionInfo VALUES(38,'2019-03-25T00:00:00','add_on_upgrade_to_notifications');
INSERT INTO VersionInfo VALUES(39,'2019-03-25T00:00:00','add_metadata_tables');
INSERT INTO VersionInfo VALUES(40,'2019-03-25T00:00:00','add_metadata_to_episodes_and_series');
INSERT INTO VersionInfo VALUES(41,'2019-03-25T00:00:00','fix_xbmc_season_images_metadata');
INSERT INTO VersionInfo VALUES(42,'2019-03-25T00:00:00','add_download_clients_table');
INSERT INTO VersionInfo VALUES(43,'2019-03-25T00:00:00','convert_config_to_download_clients');
INSERT INTO VersionInfo VALUES(44,'2019-03-25T00:00:00','fix_xbmc_episode_metadata');
INSERT INTO VersionInfo VALUES(45,'2019-03-25T00:00:00','add_indexes');
INSERT INTO VersionInfo VALUES(46,'2019-03-25T00:00:00','fix_nzb_su_url');
INSERT INTO VersionInfo VALUES(47,'2019-03-25T00:00:00','add_temporary_blacklist_columns');
INSERT INTO VersionInfo VALUES(48,'2019-03-25T00:00:00','add_title_to_scenemappings');
INSERT INTO VersionInfo VALUES(49,'2019-03-25T00:00:00','fix_dognzb_url');
INSERT INTO VersionInfo VALUES(50,'2019-03-25T00:00:00','add_hash_to_metadata_files');
INSERT INTO VersionInfo VALUES(51,'2019-03-25T00:00:00','download_client_import');
INSERT INTO VersionInfo VALUES(52,'2019-03-25T00:00:00','add_columns_for_anime');
INSERT INTO VersionInfo VALUES(53,'2019-03-25T00:00:00','add_series_sorttitle');
INSERT INTO VersionInfo VALUES(54,'2019-03-25T00:00:00','rename_profiles');
INSERT INTO VersionInfo VALUES(55,'2019-03-25T00:00:00','drop_old_profile_columns');
INSERT INTO VersionInfo VALUES(56,'2019-03-25T00:00:00','add_mediainfo_to_episodefile');
INSERT INTO VersionInfo VALUES(57,'2019-03-25T00:00:00','convert_episode_file_path_to_relative');
INSERT INTO VersionInfo VALUES(58,'2019-03-25T00:00:00','drop_episode_file_path');
INSERT INTO VersionInfo VALUES(59,'2019-03-25T00:00:00','add_enable_options_to_indexers');
INSERT INTO VersionInfo VALUES(60,'2019-03-25T00:00:00','remove_enable_from_indexers');
INSERT INTO VersionInfo VALUES(61,'2019-03-25T00:00:00','clear_bad_scene_names');
INSERT INTO VersionInfo VALUES(62,'2019-03-25T00:00:00','convert_quality_models');
INSERT INTO VersionInfo VALUES(63,'2019-03-25T00:00:00','add_remotepathmappings');
INSERT INTO VersionInfo VALUES(64,'2019-03-25T00:00:00','remove_method_from_logs');
INSERT INTO VersionInfo VALUES(65,'2019-03-25T00:00:00','make_scene_numbering_nullable');
INSERT INTO VersionInfo VALUES(66,'2019-03-25T00:00:00','add_tags');
INSERT INTO VersionInfo VALUES(67,'2019-03-25T00:00:00','add_added_to_series');
INSERT INTO VersionInfo VALUES(68,'2019-03-25T00:00:00','add_release_restrictions');
INSERT INTO VersionInfo VALUES(69,'2019-03-25T00:00:00','quality_proper');
INSERT INTO VersionInfo VALUES(70,'2019-03-25T00:00:00','delay_profile');
INSERT INTO VersionInfo VALUES(71,'2019-03-25T00:00:00','unknown_quality_in_profile');
INSERT INTO VersionInfo VALUES(72,'2019-03-25T00:00:00','history_downloadId');
INSERT INTO VersionInfo VALUES(73,'2019-03-25T00:00:00','clear_ratings');
INSERT INTO VersionInfo VALUES(74,'2019-03-25T00:00:00','disable_eztv');
INSERT INTO VersionInfo VALUES(75,'2019-03-25T00:00:00','force_lib_update');
INSERT INTO VersionInfo VALUES(76,'2019-03-25T00:00:00','add_users_table');
INSERT INTO VersionInfo VALUES(77,'2019-03-25T00:00:00','add_add_options_to_series');
INSERT INTO VersionInfo VALUES(78,'2019-03-25T00:00:00','add_commands_table');
INSERT INTO VersionInfo VALUES(79,'2019-03-25T00:00:00','dedupe_tags');
INSERT INTO VersionInfo VALUES(81,'2019-03-25T00:00:00','move_dot_prefix_to_transmission_category');
INSERT INTO VersionInfo VALUES(82,'2019-03-25T00:00:00','add_fanzub_settings');
INSERT INTO VersionInfo VALUES(83,'2019-03-25T00:00:00','additonal_blacklist_columns');
INSERT INTO VersionInfo VALUES(84,'2019-03-25T00:00:00','update_quality_minmax_size');
INSERT INTO VersionInfo VALUES(85,'2019-03-25T00:00:00','expand_transmission_urlbase');
INSERT INTO VersionInfo VALUES(86,'2019-03-25T00:00:00','pushbullet_device_ids');
INSERT INTO VersionInfo VALUES(87,'2019-03-25T00:00:00','remove_eztv');
INSERT INTO VersionInfo VALUES(88,'2019-03-25T00:00:00','pushbullet_devices_channels_list');
INSERT INTO VersionInfo VALUES(89,'2019-03-25T00:00:00','add_on_rename_to_notifcations');
INSERT INTO VersionInfo VALUES(90,'2019-03-25T00:00:00','update_kickass_url');
INSERT INTO VersionInfo VALUES(91,'2019-03-25T00:00:00','added_indexerstatus');
INSERT INTO VersionInfo VALUES(92,'2019-03-25T00:00:00','add_unverifiedscenenumbering');
INSERT INTO VersionInfo VALUES(93,'2019-03-25T00:00:00','naming_config_replace_illegal_characters');
INSERT INTO VersionInfo VALUES(94,'2019-03-25T00:00:00','add_tvmazeid');
INSERT INTO VersionInfo VALUES(95,'2019-03-25T00:00:00','add_additional_episodes_index');
INSERT INTO VersionInfo VALUES(96,'2019-03-25T00:00:00','disable_kickass');
INSERT INTO VersionInfo VALUES(97,'2019-03-25T00:00:00','add_reason_to_pending_releases');
INSERT INTO VersionInfo VALUES(98,'2019-03-25T00:00:00','remove_titans_of_tv');
INSERT INTO VersionInfo VALUES(99,'2019-03-25T00:00:00','extra_and_subtitle_files');
INSERT INTO VersionInfo VALUES(100,'2019-03-25T00:00:00','add_scene_season_number');
INSERT INTO VersionInfo VALUES(101,'2019-03-25T00:00:00','add_ultrahd_quality_in_profiles');
INSERT INTO VersionInfo VALUES(103,'2019-03-25T00:00:00','fix_metadata_file_extensions');
INSERT INTO VersionInfo VALUES(104,'2019-03-25T00:00:00','remove_kickass');
INSERT INTO VersionInfo VALUES(105,'2019-03-25T00:00:00','rename_torrent_downloadstation');
INSERT INTO VersionInfo VALUES(106,'2019-03-25T00:00:00','update_btn_url');
INSERT INTO VersionInfo VALUES(107,'2019-03-25T00:00:00','remove_wombles');
INSERT INTO VersionInfo VALUES(108,'2019-03-25T00:00:00','fix_extra_file_extension');
INSERT INTO VersionInfo VALUES(109,'2019-03-25T00:00:00','import_extra_files');
INSERT INTO VersionInfo VALUES(110,'2019-03-25T00:00:00','fix_extra_files_config');
INSERT INTO VersionInfo VALUES(112,'2019-03-25T00:00:00','added_regex_to_scenemapping');
INSERT INTO VersionInfo VALUES(113,'2019-03-25T00:00:00','consolidate_indexer_baseurl');
INSERT INTO VersionInfo VALUES(114,'2019-03-25T00:00:00','rename_indexer_status_id');
INSERT INTO VersionInfo VALUES(115,'2019-03-25T00:00:00','add_downloadclient_status');
INSERT INTO VersionInfo VALUES(116,'2019-03-25T00:00:00','disable_nyaa');
INSERT INTO VersionInfo VALUES(118,'2019-03-25T00:00:00','add_history_eventType_index');
INSERT INTO VersionInfo VALUES(120,'2019-03-25T00:00:00','update_series_episodes_history_indexes');
INSERT INTO VersionInfo VALUES(121,'2019-03-25T00:00:00','update_animetosho_url');
INSERT INTO VersionInfo VALUES(129,'2019-03-25T00:00:00','add_relative_original_path_to_episode_file');
INSERT INTO VersionInfo VALUES(130,'2019-03-25T00:00:00','episode_last_searched_time');
CREATE TABLE IF NOT EXISTS "Config" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Key" TEXT NOT NULL, "Value" TEXT NOT NULL);
INSERT INTO Config VALUES(1,'enablecompleteddownloadhandling','True');
CREATE TABLE IF NOT EXISTS "RootFolders" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Path" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "ScheduledTasks" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TypeName" TEXT NOT NULL, "Interval" INTEGER NOT NULL, "LastExecution" DATETIME NOT NULL);
INSERT INTO ScheduledTasks VALUES(1,'NzbDrone.Core.Download.CheckForFinishedDownloadCommand',1,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(2,'NzbDrone.Core.Messaging.Commands.MessagingCleanupCommand',5,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(3,'NzbDrone.Core.Update.Commands.ApplicationUpdateCommand',360,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(4,'NzbDrone.Core.DataAugmentation.Scene.UpdateSceneMappingCommand',180,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(5,'NzbDrone.Core.HealthCheck.CheckHealthCommand',360,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(6,'NzbDrone.Core.Tv.Commands.RefreshSeriesCommand',720,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(7,'NzbDrone.Core.Housekeeping.HousekeepingCommand',1440,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(8,'NzbDrone.Core.Backup.BackupCommand',10080,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(9,'NzbDrone.Core.Indexers.RssSyncCommand',15,'2019-03-25 00:00:00.000000Z');
INSERT INTO ScheduledTasks VALUES(10,'NzbDrone.Core.MediaFiles.Commands.DownloadedEpisodesScanCommand',1,'2019-03-25 00:00:00.000000Z');
CREATE TABLE IF NOT EXISTS "History" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "EpisodeId" INTEGER NOT NULL, "SeriesId" INTEGER NOT NULL, "SourceTitle" TEXT NOT NULL, "Date" DATETIME NOT NULL, "Quality" TEXT NOT NULL, "Data" TEXT NOT NULL, "EventType" INTEGER, "DownloadId" TEXT);
CREATE TABLE IF NOT EXISTS "Episodes" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "SeasonNumber" INTEGER NOT NULL, "EpisodeNumber" INTEGER NOT NULL, "Title" TEXT, "Overview" TEXT, "EpisodeFileId" INTEGER, "AbsoluteEpisodeNumber" INTEGER, "SceneAbsoluteEpisodeNumber" INTEGER, "SceneSeasonNumber" INTEGER, "SceneEpisodeNumber" INTEGER, "Monitored" INTEGER, "AirDateUtc" DATETIME, "AirDate" TEXT, "Ratings" TEXT, "Images" TEXT, "UnverifiedSceneNumbering" INTEGER NOT NULL DEFAULT 0, "LastSearchTime" DATETIME);
CREATE TABLE IF NOT EXISTS "Blacklist" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "EpisodeIds" TEXT NOT NULL, "SourceTitle" TEXT NOT NULL, "Quality" TEXT NOT NULL, "Date" DATETIME NOT NULL, "PublishedDate" DATETIME, "Size" INTEGER, "Protocol" INTEGER, "Indexer" TEXT, "Message" TEXT, "TorrentInfoHash" TEXT);
CREATE TABLE IF NOT EXISTS "NamingConfig" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "MultiEpisodeStyle" INTEGER NOT NULL, "RenameEpisodes" INTEGER, "StandardEpisodeFormat" TEXT, "DailyEpisodeFormat" TEXT, "SeasonFolderFormat" TEXT, "SeriesFolderFormat" TEXT, "AnimeEpisodeFormat" TEXT, "ReplaceIllegalCharacters" INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS "Metadata" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Enable" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT NOT NULL, "ConfigContract" TEXT NOT NULL);
INSERT INTO Metadata VALUES(1,0,'WDTV','WdtvMetadata',replace('{\n  "episodeMetadata": true,\n  "seriesImages": true,\n  "seasonImages": true,\n  "episodeImages": true,\n  "isValid": true\n}','\n',char(10)),'WdtvMetadataSettings');
INSERT INTO Metadata VALUES(2,0,'Roksbox','RoksboxMetadata',replace('{\n  "episodeMetadata": true,\n  "seriesImages": true,\n  "seasonImages": true,\n  "episodeImages": true,\n  "isValid": true\n}','\n',char(10)),'RoksboxMetadataSettings');
INSERT INTO Metadata VALUES(3,0,'Emby (Legacy)','MediaBrowserMetadata',replace('{\n  "seriesMetadata": true,\n  "isValid": true\n}','\n',char(10)),'MediaBrowserMetadataSettings');
INSERT INTO Metadata VALUES(4,0,'Kodi (XBMC) / Emby','XbmcMetadata',replace('{\n  "seriesMetadata": true,\n  "episodeMetadata": true,\n  "seriesImages": true,\n  "seasonImages": true,\n  "episodeImages": true,\n  "isValid": true\n}','\n',char(10)),'XbmcMetadataSettings');
CREATE TABLE IF NOT EXISTS "PendingReleases" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "Title" TEXT NOT NULL, "Added" DATETIME NOT NULL, "ParsedEpisodeInfo" TEXT NOT NULL, "Release" TEXT NOT NULL, "Reason" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "Series" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TvdbId" INTEGER NOT NULL, "TvRageId" INTEGER NOT NULL, "ImdbId" TEXT, "Title" TEXT NOT NULL, "TitleSlug" TEXT, "CleanTitle" TEXT NOT NULL, "Status" INTEGER NOT NULL, "Overview" TEXT, "AirTime" TEXT, "Images" TEXT NOT NULL, "Path" TEXT NOT NULL, "Monitored" INTEGER NOT NULL, "SeasonFolder" INTEGER NOT NULL, "LastInfoSync" DATETIME, "LastDiskSync" DATETIME, "Runtime" INTEGER NOT NULL, "SeriesType" INTEGER NOT NULL, "Network" TEXT, "UseSceneNumbering" INTEGER NOT NULL, "FirstAired" DATETIME, "NextAiring" DATETIME, "Year" INTEGER, "Seasons" TEXT, "Actors" TEXT, "Ratings" TEXT, "Genres" TEXT, "Certification" TEXT, "SortTitle" TEXT, "ProfileId" INTEGER, "Tags" TEXT, "Added" DATETIME, "AddOptions" TEXT, "TvMazeId" INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "EpisodeFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "Quality" TEXT NOT NULL, "Size" INTEGER NOT NULL, "DateAdded" DATETIME NOT NULL, "SeasonNumber" INTEGER NOT NULL, "SceneName" TEXT, "ReleaseGroup" TEXT, "MediaInfo" TEXT, "RelativePath" TEXT, "OriginalFilePath" TEXT);
CREATE TABLE IF NOT EXISTS "Indexers" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT, "ConfigContract" TEXT, "EnableRss" INTEGER, "EnableSearch" INTEGER);
CREATE TABLE IF NOT EXISTS "DownloadClients" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Enable" INTEGER NOT NULL, "Name" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "Settings" TEXT NOT NULL, "ConfigContract" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "RemotePathMappings" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Host" TEXT NOT NULL, "RemotePath" TEXT NOT NULL, "LocalPath" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "Restrictions" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Required" TEXT, "Preferred" TEXT, "Ignored" TEXT, "Tags" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "DelayProfiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "EnableUsenet" INTEGER NOT NULL, "EnableTorrent" INTEGER NOT NULL, "PreferredProtocol" INTEGER NOT NULL, "UsenetDelay" INTEGER NOT NULL, "TorrentDelay" INTEGER NOT NULL, "Order" INTEGER NOT NULL, "Tags" TEXT NOT NULL);
INSERT INTO DelayProfiles VALUES(1,1,1,1,0,0,2147483647,'[]');
CREATE TABLE IF NOT EXISTS "Profiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Cutoff" INTEGER NOT NULL, "Items" TEXT NOT NULL, "Language" INTEGER);
INSERT INTO Profiles VALUES(1,'Any',1,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": true\n  },\n  {\n    "quality": 8,\n    "allowed": true\n  },\n  {\n    "quality": 2,\n    "allowed": true\n  },\n  {\n    "quality": 4,\n    "allowed": true\n  },\n  {\n    "quality": 9,\n    "allowed": true\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": true\n  },\n  {\n    "quality": 6,\n    "allowed": true\n  },\n  {\n    "quality": 3,\n    "allowed": true\n  },\n  {\n    "quality": 7,\n    "allowed": true\n  },\n  {\n    "quality": 16,\n    "allowed": false\n  },\n  {\n    "quality": 18,\n    "allowed": false\n  },\n  {\n    "quality": 19,\n    "allowed": false\n  }\n]','\n',char(10)),1);
INSERT INTO Profiles VALUES(2,'SD',1,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": true\n  },\n  {\n    "quality": 8,\n    "allowed": true\n  },\n  {\n    "quality": 2,\n    "allowed": true\n  },\n  {\n    "quality": 4,\n    "allowed": false\n  },\n  {\n    "quality": 9,\n    "allowed": false\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": false\n  },\n  {\n    "quality": 6,\n    "allowed": false\n  },\n  {\n    "quality": 3,\n    "allowed": false\n  },\n  {\n    "quality": 7,\n    "allowed": false\n  },\n  {\n    "quality": 16,\n    "allowed": false\n  },\n  {\n    "quality": 18,\n    "allowed": false\n  },\n  {\n    "quality": 19,\n    "allowed": false\n  }\n]','\n',char(10)),1);
INSERT INTO Profiles VALUES(3,'HD-720p',4,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": false\n  },\n  {\n    "quality": 8,\n    "allowed": false\n  },\n  {\n    "quality": 2,\n    "allowed": false\n  },\n  {\n    "quality": 4,\n    "allowed": true\n  },\n  {\n    "quality": 9,\n    "allowed": false\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": true\n  },\n  {\n    "quality": 6,\n    "allowed": true\n  },\n  {\n    "quality": 3,\n    "allowed": false\n  },\n  {\n    "quality": 7,\n    "allowed": false\n  },\n  {\n    "quality": 16,\n    "allowed": false\n  },\n  {\n    "quality": 18,\n    "allowed": false\n  },\n  {\n    "quality": 19,\n    "allowed": false\n  }\n]','\n',char(10)),1);
INSERT INTO Profiles VALUES(4,'HD-1080p',9,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": false\n  },\n  {\n    "quality": 8,\n    "allowed": false\n  },\n  {\n    "quality": 2,\n    "allowed": false\n  },\n  {\n    "quality": 4,\n    "allowed": false\n  },\n  {\n    "quality": 9,\n    "allowed": true\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": false\n  },\n  {\n    "quality": 6,\n    "allowed": false\n  },\n  {\n    "quality": 3,\n    "allowed": true\n  },\n  {\n    "quality": 7,\n    "allowed": true\n  },\n  {\n    "quality": 16,\n    "allowed": false\n  },\n  {\n    "quality": 18,\n    "allowed": false\n  },\n  {\n    "quality": 19,\n    "allowed": false\n  }\n]','\n',char(10)),1);
INSERT INTO Profiles VALUES(5,'Ultra-HD',16,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": false\n  },\n  {\n    "quality": 8,\n    "allowed": false\n  },\n  {\n    "quality": 2,\n    "allowed": false\n  },\n  {\n    "quality": 4,\n    "allowed": false\n  },\n  {\n    "quality": 9,\n    "allowed": false\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": false\n  },\n  {\n    "quality": 6,\n    "allowed": false\n  },\n  {\n    "quality": 3,\n    "allowed": false\n  },\n  {\n    "quality": 7,\n    "allowed": false\n  },\n  {\n    "quality": 16,\n    "allowed": true\n  },\n  {\n    "quality": 18,\n    "allowed": true\n  },\n  {\n    "quality": 19,\n    "allowed": true\n  }\n]','\n',char(10)),1);
INSERT INTO Profiles VALUES(6,'HD - 720p/1080p',4,replace('[\n  {\n    "quality": 0,\n    "allowed": false\n  },\n  {\n    "quality": 1,\n    "allowed": false\n  },\n  {\n    "quality": 8,\n    "allowed": false\n  },\n  {\n    "quality": 2,\n    "allowed": false\n  },\n  {\n    "quality": 4,\n    "allowed": true\n  },\n  {\n    "quality": 9,\n    "allowed": true\n  },\n  {\n    "quality": 10,\n    "allowed": false\n  },\n  {\n    "quality": 5,\n    "allowed": true\n  },\n  {\n    "quality": 6,\n    "allowed": true\n  },\n  {\n    "quality": 3,\n    "allowed": true\n  },\n  {\n    "quality": 7,\n    "allowed": true\n  },\n  {\n    "quality": 16,\n    "allowed": false\n  },\n  {\n    "quality": 18,\n    "allowed": false\n  },\n  {\n    "quality": 19,\n    "allowed": false\n  }\n]','\n',char(10)),1);
CREATE TABLE IF NOT EXISTS "Users" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Identifier" TEXT NOT NULL, "Username" TEXT NOT NULL, "Password" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "Commands" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "Body" TEXT NOT NULL, "Priority" INTEGER NOT NULL, "Status" INTEGER NOT NULL, "QueuedAt" DATETIME NOT NULL, "StartedAt" DATETIME, "EndedAt" DATETIME, "Duration" TEXT, "Exception" TEXT, "Trigger" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "Tags" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Label" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "QualityDefinitions" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Quality" INTEGER NOT NULL, "Title" TEXT NOT NULL, "MinSize" NUMERIC, "MaxSize" NUMERIC);
INSERT INTO QualityDefinitions VALUES(1,0,'Unknown',0,100);
INSERT INTO QualityDefinitions VALUES(2,1,'SDTV',0,100);
INSERT INTO QualityDefinitions VALUES(3,8,'WEBDL-480p',0,100);
INSERT INTO QualityDefinitions VALUES(4,2,'DVD',0,100);
INSERT INTO QualityDefinitions VALUES(5,4,'HDTV-720p',0,100);
INSERT INTO QualityDefinitions VALUES(6,9,'HDTV-1080p',0,100);
INSERT INTO QualityDefinitions VALUES(7,10,'Raw-HD',0,NULL);
INSERT INTO QualityDefinitions VALUES(8,5,'WEBDL-720p',0,100);
INSERT INTO QualityDefinitions VALUES(9,6,'Bluray-720p',0,100);
INSERT INTO QualityDefinitions VALUES(10,3,'WEBDL-1080p',0,100);
INSERT INTO QualityDefinitions VALUES(11,7,'Bluray-1080p',0,100);
INSERT INTO QualityDefinitions VALUES(12,16,'HDTV-2160p',0,NULL);
INSERT INTO QualityDefinitions VALUES(13,18,'WEBDL-2160p',0,NULL);
INSERT INTO QualityDefinitions VALUES(14,19,'Bluray-2160p',0,NULL);
CREATE TABLE IF NOT EXISTS "Notifications" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Name" TEXT NOT NULL, "OnGrab" INTEGER NOT NULL, "OnDownload" INTEGER NOT NULL, "Settings" TEXT NOT NULL, "Implementation" TEXT NOT NULL, "ConfigContract" TEXT, "OnUpgrade" INTEGER, "Tags" TEXT, "OnRename" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "ExtraFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "SeasonNumber" INTEGER NOT NULL, "EpisodeFileId" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "Extension" TEXT NOT NULL, "Added" DATETIME NOT NULL, "LastUpdated" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "SubtitleFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "SeasonNumber" INTEGER NOT NULL, "EpisodeFileId" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "Extension" TEXT NOT NULL, "Added" DATETIME NOT NULL, "LastUpdated" DATETIME NOT NULL, "Language" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "MetadataFiles" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "SeriesId" INTEGER NOT NULL, "Consumer" TEXT NOT NULL, "Type" INTEGER NOT NULL, "RelativePath" TEXT NOT NULL, "LastUpdated" DATETIME NOT NULL, "SeasonNumber" INTEGER, "EpisodeFileId" INTEGER, "Hash" TEXT, "Added" DATETIME, "Extension" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "SceneMappings" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TvdbId" INTEGER NOT NULL, "SeasonNumber" INTEGER, "SearchTerm" TEXT NOT NULL, "ParseTerm" TEXT NOT NULL, "Title" TEXT, "Type" TEXT, "SceneSeasonNumber" INTEGER, "FilterRegex" TEXT);
CREATE TABLE IF NOT EXISTS "IndexerStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME, "LastRssSyncReleaseInfo" TEXT);
CREATE TABLE IF NOT EXISTS "DownloadClientStatus" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ProviderId" INTEGER NOT NULL, "InitialFailure" DATETIME, "MostRecentFailure" DATETIME, "EscalationLevel" INTEGER NOT NULL, "DisabledTill" DATETIME);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Episodes',0);
INSERT INTO sqlite_sequence VALUES('NamingConfig',0);
INSERT INTO sqlite_sequence VALUES('Config',1);
INSERT INTO sqlite_sequence VALUES('Series',0);
INSERT INTO sqlite_sequence VALUES('EpisodeFiles',0);
INSERT INTO sqlite_sequence VALUES('Indexers',0);
INSERT INTO sqlite_sequence VALUES('DownloadClients',0);
INSERT INTO sqlite_sequence VALUES('DelayProfiles',1);
INSERT INTO sqlite_sequence VALUES('Profiles',6);
INSERT INTO sqlite_sequence VALUES('Tags',0);
INSERT INTO sqlite_sequence VALUES('QualityDefinitions',14);
INSERT INTO sqlite_sequence VALUES('Notifications',0);
INSERT INTO sqlite_sequence VALUES('MetadataFiles',0);
INSERT INTO sqlite_sequence VALUES('SceneMappings',0);
INSERT INTO sqlite_sequence VALUES('IndexerStatus',0);
INSERT INTO sqlite_sequence VALUES('ScheduledTasks',10);
INSERT INTO sqlite_sequence VALUES('Metadata',4);
CREATE UNIQUE INDEX "UC_Version" ON "VersionInfo" ("Version" ASC);
CREATE UNIQUE INDEX "IX_Config_Key" ON "Config" ("Key" ASC);
CREATE UNIQUE INDEX "IX_RootFolders_Path" ON "RootFolders" ("Path" ASC);
CREATE UNIQUE INDEX "IX_ScheduledTasks_TypeName" ON "ScheduledTasks" ("TypeName" ASC);
CREATE INDEX "IX_Blacklist_SeriesId" ON "Blacklist" ("SeriesId" ASC);
CREATE INDEX "IX_Episodes_EpisodeFileId" ON "Episodes" ("EpisodeFileId" ASC);
CREATE INDEX "IX_Episodes_SeriesId" ON "Episodes" ("SeriesId" ASC);
CREATE INDEX "IX_History_Date" ON "History" ("Date" ASC);
CREATE UNIQUE INDEX "IX_Series_TvdbId" ON "Series" ("TvdbId" ASC);
CREATE UNIQUE INDEX "IX_Series_TitleSlug" ON "Series" ("TitleSlug" ASC);
CREATE INDEX "IX_Series_Path" ON "Series" ("Path" ASC);
CREATE INDEX "IX_Series_CleanTitle" ON "Series" ("CleanTitle" ASC);
CREATE INDEX "IX_Series_TvRageId" ON "Series" ("TvRageId" ASC);
CREATE INDEX "IX_EpisodeFiles_SeriesId" ON "EpisodeFiles" ("SeriesId" ASC);
CREATE UNIQUE INDEX "IX_Indexers_Name" ON "Indexers" ("Name" ASC);
CREATE UNIQUE INDEX "IX_QualityProfiles_Name" ON "Profiles" ("Name" ASC);
CREATE UNIQUE INDEX "IX_Users_Identifier" ON "Users" ("Identifier" ASC);
CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username" ASC);
CREATE UNIQUE INDEX "IX_Tags_Label" ON "Tags" ("Label" ASC);
CREATE UNIQUE INDEX "IX_QualityDefinitions_Quality" ON "QualityDefinitions" ("Quality" ASC);
CREATE UNIQUE INDEX "IX_QualityDefinitions_Title" ON "QualityDefinitions" ("Title" ASC);
CREATE INDEX "IX_Series_TvMazeId" ON "Series" ("TvMazeId" ASC);
CREATE INDEX "IX_Episodes_SeriesId_SeasonNumber_EpisodeNumber" ON "Episodes" ("SeriesId" ASC, "SeasonNumber" ASC, "EpisodeNumber" ASC);
CREATE UNIQUE INDEX "IX_IndexerStatus_ProviderId" ON "IndexerStatus" ("ProviderId" ASC);
CREATE UNIQUE INDEX "IX_DownloadClientStatus_ProviderId" ON "DownloadClientStatus" ("ProviderId" ASC);
CREATE INDEX "IX_History_EventType" ON "History" ("EventType" ASC);
CREATE INDEX "IX_Episodes_SeriesId_AirDate" ON "Episodes" ("SeriesId" ASC, "AirDate" ASC);
CREATE INDEX "IX_History_EpisodeId_Date" ON "History" ("EpisodeId" ASC, "Date" DESC);
CREATE INDEX "IX_History_DownloadId_Date" ON "History" ("DownloadId" ASC, "Date" DESC);
COMMIT;
